name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      - uses: subosito/flutter-action@v2.21.0
        with:
          flutter-version: "3.35.7"
      - run: |
          flutter pub get
          flutter build apk --release
      - uses: actions/upload-artifact@v5.0.0
        with:
          name: build-android
          path: build/app/outputs/flutter-apk/app-release.apk
